### ISSUE TITLE
Feature Reqest: Multilanguage Support

### ISSUE THREAD

**Issue by mtonnie** [cdubz/babybuddy#62]
I guess it would be very nice to enable translation other languages.
In my special case it's german, but I guess others are interresting too.

### TODO
- [x] Enable i18n and locale support in base settings.
- [x] Add `gulp` commands for `makemessages` and `compilemessages`.
- [x] Refactor `babybuddy` app with translatable strings.
- [x] Refactor `core` app with translatable strings.
- [x] Refactor `dashboard` app with translatable strings.
- [x] Refactor `reports` app with translatable strings.
- [x] Refactor all Python formatted strings to be translatable (just putting this off because I didn't immediately understand how to do it...).
- [x] Refactor all javascript with translatable strings.
- [x] Store/use language from user Setting field.
- [x] Add tests.
- [x] Find/set up translation tie-in service for easier contribution.
- [x] Add documentation for translation process/support.

### References
- [Translation | Django documentation](https://docs.djangoproject.com/en/2.2/topics/i18n/translation/)
- [Friendly howto for translators](http://docs.translatehouse.org/projects/localization-guide/en/latest/guide/project/howto.html)

**Comment by cdubz** [comment]
Yes, I have been meaning to do this for a long time since it is already well supported in Django. I’ve just needed to research best practices for sourcing actual translations. Happy to take any advice (:

I’ll start looking in to this soon.

**Comment by cdubz** [comment]
FTR I have started work on this in the [i18n branch](/cdubz/babybuddy/tree/i18n).

### TODO
- [x] Enable i18n and locale support in base settings.
- [x] Add `gulp` commands for `makemessages` and `compilemessages`.
- [x] Refactor `babybuddy` app with translatable strings.
- [x] Refactor `core` app with translatable strings.
- [ ] Refactor `dashboard` app with translatable strings.
- [ ] Refactor `reports` app with translatable strings.
- [ ] Refactor all Python formatted strings to be translatable (just putting this off because I didn't immediately understand how to do it...).
- [ ] Refactor all javascript with translatable strings.
- [ ] Add documentation for translation process/support.
- [ ] Find/set up translation tie-in service for easier contribution.

### References:
[Translation | Django documentation](https://docs.djangoproject.com/en/2.2/topics/i18n/translation/)

**Comment by cdubz** [comment]
Support for translation is merged in to master with #63. I have provided a (bad) French translation essentially as an example, I can't really help you with German (: I do still need to see if I can sort out some sort of integration for easier collaborative translation work...

**Comment by cdubz** [comment]
Ok, I have set up POEdtior as an integration service. @mtonnie, if you are willing and able, happy to have you help with a DE translation -- https://poeditor.com/join/project/QwQqrpTIzn.

**Comment by cdubz** [comment]
Added info re: POEditor in 8c032617b81c747ea45cb0332485f0c69b666ac3. Going to close this ticket now and we can open separate ones for specific translations.
